platform :ios, '12.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'Plugin' do
  use_frameworks!
  pod 'GoogleMaps'
  capacitor_pods
end

target 'PluginTests' do
  use_frameworks!
  pod 'GoogleMaps'
  capacitor_pods
end
